# Practice on Numpy and Pandas

Here are some task for you, to refresh what you saw in the notebooks before.

It will help you strengthen the **learning objectives** from the notebook before. You should be able to
- create numpy arrays
- manipulate them with basic mathematics operators
- extract rows, columns and items by indexing
- use aggregation methods (like sum, min, max, std) on numpy arrays


**Part 1**: Creating numpy arrays.

- Please create a numpy array from the list:
```Python
my_list = [1, 2, 5, 6, 8]
````

- Please create a numpy array containing the values from 1 to 10.
-  Please create a numpy array from 0 to 5 cwith a stepsize of 0.2
- Create a numpy array with the shape 2,3 with random values


In [2]:
#1
import numpy as np
my_list_1 = np.arange(1,11)
my_list_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#2
my_list_2 = np.arange(0,5, 0.2)
my_list_2

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [4]:
#3
my_list_3 = np.random.rand(2,3)
my_list_3

array([[0.86120731, 0.81236708, 0.68641655],
       [0.36053208, 0.37586963, 0.47166577]])

**Part 2**: Manipulate numpy arrays.

1. Please create a numpy array with (1, 3, '4', 7, 12, '0'). Define the content as integer.
2. Check the data type of the objects and the shape of the array
3. Update the 4th value to 30.
4. Reshape the array to a 2x3 matrix.
5. Please add 8 to the first row and 12 to the second row.
6. Mulitply the first column with 2, the second with 3 and the third with 4.
7. Please summ up all numbers in the first row, and all numbers in the second row.
8. Similarly, search for the largest number for each column.
9. Extract the number in the second column and the first row.
10. Check at which index the value is exactly 48.

In [43]:
#1
my_list_4 = np.array([1, 3, '4', 7, 12, '0'], np.int32)
my_list_4

array([ 1,  3,  4,  7, 12,  0], dtype=int32)

In [44]:
#2
print(type(my_list_4))
print(my_list_4.shape)

<class 'numpy.ndarray'>
(6,)


In [45]:
#3
my_list_4 = np.where(my_list_4 == 4, 30, my_list_4) 
my_list_4

array([ 1,  3, 30,  7, 12,  0], dtype=int32)

In [46]:
#4
my_list_4 = np.array(my_list_4).reshape(2, 3)
print(my_list_4)

[[ 1  3 30]
 [ 7 12  0]]


In [47]:
#5
my_list_4 = my_list_4 + [[8], [12]]
my_list_4

array([[ 9, 11, 38],
       [19, 24, 12]])

In [48]:
#6
my_list_4 = my_list_4 * [2, 3, 4]
my_list_4

array([[ 18,  33, 152],
       [ 38,  72,  48]])

In [49]:
#7
my_list_4 .sum(axis=1)

array([203, 158])

In [50]:
#8
my_list_4.max(axis=0)

array([ 38,  72, 152])

In [51]:
#9
my_list_4[:1, 1]

array([33])

In [52]:
#10
print(np.where(my_list_4 == 48))

(array([1]), array([2]))
